name: innerlibs
description: All-in-one extensions and tools to improve dart code.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto:
  intl:
  darq:
  convert:
  http: 
  async:
  mask_text_input_formatter:
  path:
  xml: 
 
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

 



