name: innerlibs
description: All-in-one extensions and tools to improve dart code.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  darq:
  collection:
  convert:
  http: 
  async:
  mask_text_input_formatter:
  path:
  xml: 
  get:
  crypto:
  intl: 
  xml_crypto:
  brasil_fields:
  path_provider:
  printing:
  download:
  file_picker:
  gap:
  dropdown_search:
  mime:
  format:
 
 
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  assets:
    - lib/brasil.json 
    - assets/fonts/consola.ttf
    - assets/fonts/consolab.ttf
    - assets/fonts/consolai.ttf 
    - assets/images/brazil.png
    - assets/images/merco.png
    - assets/images/brasaoOficial.png

  fonts:
  - family: Mandatory
    fonts:
      - asset: assets/fonts/mandatory.ttf
  - family: Fe
    fonts:
      - asset: assets/fonts/fe.ttf
  - family: Xanh
    fonts:
      - asset: assets/fonts/XanhMono-Regular.ttf

 



